### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by GGasch** [K2SOHIGH/pcalf#10]
There is a fringe issue with importlib. Version prior to 3.7 don't have importlib.resources.files which causes an error in pcalf. It should be added in the required dependencies (wonder which versions is necessary tho).

Besides Blast is available in conda and could be added as such

**Comment by K2SOHIGH** [comment]
Which version of python do you use ?

Blast can be installed manually or through conda. PCALF require that blast is in your PATH.

So if you already have blast in your PATH you can install pcalf through pip and that's all. 

The conda recipe is more complete as blast is included.

**Comment by GGasch** [comment]
Python 3.8 outside conda, but 3.9 in the conda environment I made for pcalf. For some odd reasons the issue sort of resolved itself, even though conda does not seem to have importlib >= 3.7 avaiblable, I think. I am not sure. I will look into that.

Okay for conda.

**Comment by GGasch** [comment]
I have assessed the issue. The importlib issue is directly linked to the python version used. If strictly below 3.9, importlib doesn't have the correct modules.
