### ISSUE TITLE
Error while using CheckM

### ISSUE THREAD

**Issue by GGasch** [K2SOHIGH/pcalf#12]
When running pcalf-annotate-workflow a strange error occured : 

pcalf-annotate-workflow -i pcalf_datasets_results/genomes.yaml -o pcalf_annotate_results --gtdb /run/media/guest-biom/data4/GTDB/release214 --checkm /run/media/guest-biom/data4/CheckM

Error in rule cm_bins_into_batches:
    jobid: 0
    output: /run/media/guest-biom/dat2_encrypt/Projet_Bioinfos/pcalf/231110_Scan_cyanobacteria_wt_checkm/pcalf_annotate_results/checkm-res/tmp/bins/batch_2/batch.tsv

RuleException:
KeyError in file /home/guest-biom/opt/pcalf/pcalf/workflow/annotate/rules/checkm.smk, line 205:
'batch_2'
  File "/home/guest-biom/opt/pcalf/pcalf/workflow/annotate/rules/checkm.smk", line 205, in __rule_cm_bins_into_batches
  File "/home/guest-biom/miniconda3/envs/pcalf/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

What is strange is that the processes still progressed after that.

**Comment by K2SOHIGH** [comment]
can you send me the genomes.yaml please ? What is the batch size ?

**Comment by GGasch** [comment]
[genomes.txt](https://github.com/K2SOHIGH/pcalf/files/13335050/genomes.txt)

I add to change the .yaml into .txt but it is the correct file.

What is a batch :3 ?

**Comment by GGasch** [comment]
I also add that the directory Scan_cyanobacteria_wt_checkm/pcalf_annotate_results/checkm-res/tmp/bins/batch_2 have been created, but not batch.tsv

**Comment by GGasch** [comment]
Final point on the subject. Sometimes this error kill the process. Sometimes the process is able to proceed. I have no clue as why this behaviour change

**Comment by GGasch** [comment]
The problem is clearly nested in thoses lines : 

params:
        batch = lambda wildcards:GENOMESBATCH[wildcards.batch],
run:
        batch_genomes = params.batch[str(wildcards.batch)]

I am positively terrified on how you can call a variable (wildcards) that has not been defined in the code (this rule takes no inputs)

**Comment by GGasch** [comment]
Okay. There is something fishy in genomes_into_batches() in Snakefile.
When called by cm_bins_into_batches, the function return not one dictionary but five identical dictionaries, which probably messes up the rest of the code. This behaviour is linked to INPUT.items().

**Comment by GGasch** [comment]
My current understanding of the issue is : 
_ rule cm_bins_into_batches calls GENOMESBATCH
_GENOMESBATCH seems to return not one dictionnary, but 5 identical dictionnaries at once.
_The issue seems to be linked to INPUT.items() which return 5 times the content of genomes.yaml

However INPUT.items() is not bugged. Apparently the workflow calls the GENOMESBATCH twice, and the first time everything is working fine. Only the second time the fonction returns 5 dictionaries.

**Comment by GGasch** [comment]
I also don't understand how wildcards can be defined in the run section of this rules. And I think it is somewhat important.
params:
       batch = lambda wildcards:GENOMESBATCH[wildcards.batch],
run:
        batch_genomes = params.batch[str(wildcards.batch)]

**Comment by K2SOHIGH** [comment]
I fix the broken part of the cm_bins_into_batches  rule.
